languageCode = "en"
languageName = "English"
title        = "Andrew Sulisthio"
weight       = 1

[params]
copyright     = "Andrew Kurniawan Sulisthio 2024"
dateFormat    = "2 January 2006"
description   = "Andrew Sulisthio, system developer & coffee entrepreneur"
displayName   = "EN"
isoCode       = "en"
logo          = ""
rtl           = false
secondaryLogo = ""

[author]
bio      = "Passionately developing efficient and easy-to-maintain web solutions for businesses whilst procuring and serving international connoisseurs with auction-grade coffees"
headline = "ğŸ§‘â€ğŸ’» System Developer & â˜• Coffee Entrepreneur"
image    = "img/andrew_portrait.jpg"
links    = [  ]
name     = "Andrew Sulisthio"
